version: "3.8"

services:
  postgres-z2p:
    image: postgres:latest
    container_name: z2p-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?error}
      POSTGRES_DB: ${APP_DB_NAME?error}
      APP_USER: ${APP_USER?error}
      APP_USER_PWD: ${APP_USER_PWD?error}
    ports:
      - "${POSTGRES_PORT?error}:5432"
    command: -N 1000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER?error}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./.db_data:/var/lib/postgresql/data
